directory/urls.py
from django.urls import path
from . import views

app_name = 'directory'

urlpatterns = [
 path('', views.home, name='home'),
 path('students/', views.all_students, name='all_students'),
 path('students/<int:student_id>/', views.student, name='student'),
 path('teachers/', views.all_teachers, name='all_teachers'),
 path('teachers/<int:teacher_id>/', views.teacher, name='teacher'),
]

jmcdir/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('directory.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

directory/models.py
from django.db import models

# Create your models here.
class Student(models.Model):
    lastName = models.CharField(max_length=100)
    firstName = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    contact = models.CharField(max_length=100)
    course = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    image = models.ImageField(upload_to='directory/images')

    def __str__(self):
        return self.lastName

class Teacher(models.Model):
    lastName = models.CharField(max_length=100)
    firstName = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    contact = models.IntegerField()
    course = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    image = models.ImageField(upload_to='directory/images')

    def __str__(self):
        return self.lastName

directory/views.py
from django.shortcuts import render, get_object_or_404
from .models import Teacher,Student
# Create your views here.
def home(request):
    return render(request, 'directory/home.html')

def all_students(request):
    students = Student.objects.all()
    return render(request, 'directory/students.html', {
        'students': students,
    })

def all_teachers(request):
    teachers = Teacher.objects.all()
    return render(request, 'directory/teachers.html', {
        'teachers': teachers,
    })

def student(request, student_id):
    student = get_object_or_404(Student, pk=student_id)
    students = Student.objects.all()
    return render(request, 'directory/student_details.html', {
        'student': student,
        'students': students
    })

def teacher(request, teacher_id):
    teacher = get_object_or_404(Teacher, pk=teacher_id)
    teachers = Teacher.objects.all()
    return render(request, 'directory/teacher_details.html', {
        'teacher': teacher,
        'teachers': teachers
    })

directory/templates/directory/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Vaccination Tracker</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'directory:home' %}">
        <span>Covid19 – Vaccination Tracker</span>
    </a>
        <ul class="nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'directory:home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'directory:all_students' %}">Patients</a>
          </li>
        </ul>
    </div>
  </div>
</nav>
{% block content %}
{% endblock %}
</body>
</html>

directory/templates/directory/home.html
{% extends 'directory/base.html' %}

{% block content %}
{% endblock %}

directory/templates/directory/student_details.html
{% extends 'directory/base.html' %}


{% block content %}
<div style="width: 500px; margin:50px auto">
    <div style="text-align:center; padding-bottom:50px"><img src="{{student.image.url}}" width="250" height="250"></div>

    <p>Last Name: {{student.lastName}}</p>
    <p>First Name: {{student.firstName}}</p>
    <p>Email: {{student.email}}</p>
    <p>Contact: {{student.contact}}</p>
    <p>Address: {{student.address}}</p>
    <p>Course: {{student.course}}</p>
</div>
{% endblock %}

directory/templates/directory/students.html
{% extends 'directory/base.html' %}

{% block content %}
<br>
<br>
<br>
<h1 style="text-align:center"> Covid19 patients</h1>
<br>
<br>
<table class="table">
  <thead class="table-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">LastName</th>
      <th scope="col">FirstName</th>
      <th scope="col">Contact No.</th>
        <th scope="col">Barangay</th>
        <th scope="col">Street</th>
        <th scope="col">House No.</th>
        <th scope="col">City</th>
        <th scope="col">Age</th>
        <th scope="col">Date of Birth</th>
        <th scope="col">Vaccine Name</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Kumar</td>
      <td>Phrim</td>
      <td>9097291383</td>
         <td>Lasang</td>
         <td>Tambogon</td>
         <td>12</td>
         <td>Davao</td>
         <td>40</td>
         <td>21-Apr-71</td>
         <td>Sinopharm</td>
    </tr>
    <tr class="table-danger">
      <th scope="row">2</th>
     <td>Wilson</td>
      <td>Andrew</td>
      <td>9097291388</td>
         <td>Bunawan</td>
         <td>Maduo</td>
         <td>65</td>
         <td>Davao</td>
         <td>38</td>
         <td>22-Apr-83</td>
         <td>Phyzer</td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td>Khan</td>
      <td>Sandra</td>
      <td>9097291385</td>
         <td>Tibungco</td>
         <td>Mahilum</td>
         <td>55</td>
         <td>Davao</td>
         <td>60</td>
         <td>23-Jan-62</td>
         <td>AstraZeneca</td>
    </tr>
  <tr class="table-danger">
      <th scope="row">4</th>
      <td>Bogut</td>
      <td>Andrew</td>
      <td>9097291388</td>
         <td>Buhangin</td>
         <td>Communal</td>
         <td>65</td>
         <td>Davao</td>
         <td>38</td>
         <td>22-Apr-83</td>
         <td>Phyzer</td>
  </tr>
  </tbody>
</table>
{% endblock %}

directory/templates/directory/teacher_details.html
{% extends 'directory/base.html' %}

{% block content %}
<div style="width: 500px; margin:50px auto">
    <div style="text-align:center; padding-bottom:50px"><img src="{{teacher.image.url}}" width="250" height="250"></div>
    <p>Last Name: {{teacher.lastName}}</p>
    <p>First Name: {{teacher.firstName}}</p>
    <p>Email: {{teacher.email}}</p>
    <p>Contact: {{teacher.contact}}</p>
    <p>Address: {{teacher.address}}</p>
    <p>Course: {{teacher.course}}</p>
</div>
{% endblock %}

directory/templates/directory/teachers.html
{% extends 'directory/base.html' %}

{% block content %}
<br>
<br>
<br>
<br>
<br>
<h1 style="text-align:center">Teachers</h1>
<br>
<br>
<table class="table">
  <thead>
    <tr>
    <a href=""><th scope="col">LastName</th></a>
    <th scope="col">FirstName</th>
    <th scope="col">Email</th>
    <th scope="col">Contact</th>
    <th scope="col">Course</th>
    </tr>
  </thead>
  <tbody>
    {% for teacher in teachers %}
    <tr>
      <td><a href="{% url 'directory:teacher' teacher.id %}" class="nav-link" style="color:black">{{teacher.lastName}}</a></td>
      <td><a href="{% url 'directory:teacher' teacher.id %}" class="nav-link" style="color:black">{{teacher.firstName}}</a></td>
      <td><a href="{% url 'directory:teacher' teacher.id %}">{{teacher.email}}</a></td>
      <td><a href="{% url 'directory:teacher' teacher.id %}" class="nav-link" style="color:black">{{teacher.contact}}</a></td>
      <td><a href="{% url 'directory:teacher' teacher.id %}" class="nav-link" style="color:black">{{teacher.course}}</a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}